export const FEED_SECTIONS = [
  'Breaking News',
  'Headlines',
  'India',
  'Tamil Nadu',
  'Business & Finance',
  'Economy',
  'Europe',
  'Middle East',
  'East Asia',
  'World News',
  'Technology',
  'Indian Editorials',
  'International Editorials',
  'History',
  'Geopolitics',
  'For You'
] as const;

export const TAMIL_NADU_DISTRICTS = [
  'Ramanathapuram',
  'Paramakudi',
  'Muthukulathur',
  'Chennai',
  'Vellore',
  'Tirunelveli',
  'Tiruppur',
  'Tiruvannamalai',
  'Coimbatore',
  'Tiruchirappalli',
  'Madurai',
  'Sayalgudi'
] as const;

export const FEED_REFRESH_INTERVAL_MIN = 30; // minutes
export const FEED_REFRESH_INTERVAL_MAX = 45; // minutes

export const ARTICLES_PER_SECTION = 20; // Reasonable curated count
export const MAX_ARTICLES_PER_SOURCE_PER_SECTION = 2;

export const THEMES = [
  'system',
  'light',
  'dark',
  'sepia',
  'kindleWhite',
  'kindleWarm',
  'highContrast',
  'slate'
] as const;

export const NEWS_SOURCES = [
  'https://thewire.in',
  'https://www.theguardian.com',
  'https://www.spiked-online.com',
  'https://www.scmp.com',
  'https://frontline.thehindu.com',
  'https://www.foreignaffairs.com',
  'https://www.telegraphindia.com',
  'https://www.thestatesman.com',
  'https://www.independent.co.uk',
  'https://scroll.in',
  'https://indianexpress.com',
  'https://foreignpolicy.com',
  'https://bostonreview.net',
  'https://www.currentaffairs.org',
  'https://truthdig.com',
  'https://www.972mag.com',
  'https://www.thehindubusinessline.com',
  'https://www.salon.com',
  'https://theprint.in',
  'https://www.barandbench.com',
  'https://aeon.co',
  'https://countercurrents.org',
  'https://www.middleeasteye.net',
  'https://www.indiaspend.com',
  'https://www.epw.in',
  'https://unherd.com',
  'https://www.theglobeandmail.com',
  'https://www.fdd.org',
  'https://www.nytimes.com',
  'https://www.historytoday.com',
  'https://www.dawn.com',
  'https://www.politico.com',
  'https://www.cnn.com',
  'https://www.business-standard.com',
  'https://www.ft.com',
  'https://www.wired.com',
  'https://www.politico.eu',
  'https://www.historyextra.com',
  'https://www.smithsonianmag.com',
  'https://thediplomat.com',
  'https://www.thehindu.com',
  'https://www.bbc.com',
  'https://nationalpost.com',
  'https://www.spectator.co.uk',
  'https://www.technologyreview.com',
  'https://www.scmr.com',
  'https://sloanreview.mit.edu',
  'https://hbr.org',
  'https://www.newyorker.com',
  'https://www.supplychaindive.com',
  'https://www.stimson.org',
  'https://arstechnica.com',
  'https://www.spiegel.de',
  'https://www.lemonde.fr',
  'https://www.nationalreview.com',
  'https://www.nzherald.co.nz',
  'https://www.theverge.com',
  'https://techcrunch.com',
  'https://www.gsb.stanford.edu',
  'https://www.entrepreneur.com',
  'https://www.inc.com',
  'https://www.oecd.org',
  'https://qz.com',
  'https://www.ancient-origins.net',
  'https://nationalinterest.org',
  'https://www.stratfor.com',
  'https://www.fastcompany.com',
  'https://www.orfonline.org',
  'https://www.lowyinstitute.org',
  'https://www.pbs.org',
  'https://www.propublica.org',
  'https://www.project-syndicate.org',
  'https://daily.jstor.org',
  'https://www.space.com',
  'https://asiatimes.com',
  'https://theconversation.com',
  'https://asia.nikkei.com',
  'https://www.piie.com',
  'https://www.csis.org',
  'https://carnegieendowment.org',
  'https://www.hoover.org',
  'https://notesfrompoland.com',
  'https://news.harvard.edu',
  'https://www.scientificamerican.com',
  'https://www.quantamagazine.org',
  'https://www.astronomy.com',
  'https://skyandtelescope.org',
  'https://www.cfr.org',
  'https://www.chathamhouse.org',
  'https://timesca.com',
  'https://www.themoscowtimes.com',
  'https://www.thelocal.com',
  'https://www.aljazeera.com',
  'https://www.thebarentsobserver.com',
  'https://www.thebaltictimes.com',
  'https://www.cna.asia',
  'https://www.straitstimes.com',
  'https://balkaninsight.com',
  'https://kyivindependent.com',
  'https://www.smh.com.au',
  'https://www.businessinsider.com',
  'https://www.jpost.com',
  'https://www.prospectmagazine.co.uk',
  'https://www.japantimes.co.jp',
  'https://www.abc.net.au',
  'https://time.com',
  'https://www.npr.org',
  'https://apnews.com',
  'https://www.reuters.com',
  'https://www.forbes.com',
  'https://www.lrb.co.uk',
  'https://greatergood.berkeley.edu',
  'https://nautil.us',
  'https://www.psychologytoday.com',
  'https://popular-archaeology.com',
  'https://archaeology.org',
  'https://www.nature.com',
  'https://www.newscientist.com',
  'https://www.skyatnightmagazine.com',
  'https://www.cnbc.com',
  'https://www.bangkokpost.com',
  'https://jordantimes.com',
  'https://english.aawsat.com',
  'https://www.theaustralian.com.au',
  'https://www.history.com',
  'https://www.nationalgeographic.com',
  'https://thewalrus.ca',
  'https://www.chicagotribune.com',
  'https://www.newstatesman.com',
  'https://www.scotsman.com',
  'https://www.heraldscotland.com',
  'https://www.dallasnews.com',
  'https://www.houstonchronicle.com',
  'https://www.seattletimes.com',
  'https://www.denverpost.com',
  'https://www.miamiherald.com',
  'https://www.sfchronicle.com',
  'https://www.dailytelegraph.com.au',
  'https://www.latimes.com',
  'https://www.newslaundry.com',
  'https://www.scoop.co.nz',
  'https://quillette.com',
  'https://thespinoff.co.nz',
  'https://newsroom.co.nz',
  'https://thetyee.ca',
  'https://independentaustralia.net',
  'https://www.thesaturdaypaper.com.au',
  'https://michaelwest.com.au',
  'https://www.crikey.com.au',
  'https://www.thecanary.co',
  'https://bylinetimes.com',
  'https://www.csmonitor.com',
  'https://jacobin.com',
  'https://www.motherjones.com',
  'https://newrepublic.com',
  'https://www.texastribune.org',
  'https://theintercept.com',
  'https://www.thenation.com',
  'https://eurasianet.org',
  'https://hbs.edu',
  'https://mondediplo.com',
  'https://novaramedia.com',
  'https://tribunemag.co.uk',
  'https://newint.org',
  'https://guido-fawkes.com',
  'https://www.vox.com',
  'https://www.nbcnews.com',
  'https://www.dtnext.in',
  'https://www.sixthtone.com',
  'https://www.asahi.com',
  'https://www.koreaherald.com',
  'https://www.jadaliyya.com',
  'https://www.thestreet.com',
  'https://www.businessdailyafrica.com',
  'https://smallbiztrends.com',
  'https://www.marketwatch.com',
  'https://www.imf.org',
  'https://kpmg.com',
  'https://www.ey.com',
  'https://www.pwc.com',
  'https://www2.deloitte.com',
  'https://www.bain.com',
  'https://www.bcg.com',
  'https://www.eastasiaforum.org',
  'https://middleeastmonitor.com',
  'https://ai-monitor.ai',
  'https://www.rollingstone.com',
  'https://www.kiplinger.com',
  'https://www.economictimes.indiatimes.com',
  'https://www.barrons.com',
  'https://www.zacks.com',
  'https://seekingalpha.com',
  'https://www.fool.com',
  'https://www.morningstar.com',
  'https://venturebeat.com',
  'https://www.gartner.com',
  'https://spectrum.ieee.org',
  'https://www.infoworld.com',
  'https://www.theregister.com',
  'https://www.financialexpress.com',
  'https://www.washingtonpost.com',
  'https://www.theatlantic.com',
  'https://timesofindia.indiatimes.com',
  'https://economictimes.indiatimes.com/realty',
  'https://www.tamilguardian.com',
  'https://www.aboutamazon.com'
] as const;

export const FOLLOWED_TOPICS = [
  'Management',
  'Personal Development',
  'Entrepreneurship',
  'Ukraine',
  'Russo-Ukrainian war',
  'Group of Seven',
  'Russian Revolution',
  'French Revolution',
  'People\'s Liberation Army',
  'Balochistan',
  'Switzerland',
  'Globalization',
  'BRICS',
  'G20',
  'Myanmar (Burma)',
  'Sri Lanka',
  'Bangladesh',
  'Pakistan',
  'Communist Party of China',
  'Balkans',
  'East India Company',
  'British Raj',
  'Ancient history',
  'Marketing strategy',
  'Marketing management',
  'Soviet Union',
  'Tamil Nadu State Department of Archaeology',
  'Industrial Revolution',
  'Middle Ages',
  'Age of Enlightenment',
  'The Great Depression',
  'Cold War',
  'Civil rights movement',
  'British Empire',
  'Roman Empire',
  'American Civil War',
  'American Revolution',
  'World War II',
  'World War I',
  'Leadership',
  'Investment banking',
  'New Zealand',
  'Quantum Computing',
  'Quantum mechanics',
  'Iran',
  'Taiwan',
  'E-Commerce',
  'Science',
  'History',
  'Israel',
  'Stock market',
  'Italy',
  'France',
  'Germany',
  'Canada',
  'United Kingdom',
  'Russia',
  'International affairs',
  'European Union',
  'North Korea',
  'South Korea',
  'Japan',
  'Singapore',
  'Hong Kong',
  'China',
  'Asia',
  'Australia',
  'Europe',
  'Brookings Institution',
  'Supply chain management',
  'Archaeological Survey of India',
  'Archaeology',
  'Marketing',
  'Emotional intelligence',
  'Consciousness',
  'Currency',
  'Inflation',
  'World economy',
  'Economy',
  'Cryptocurrencies',
  'Space',
  'Universe',
  'Economics',
  'Artificial intelligence',
  'World news',
  'Geopolitics',
  'Business',
  'Finance',
  'Technology',
  'Tamil Nadu',
  'Gilded Age',
  'Sales',
  'Systems thinking',
  'Historian',
  'Crusades',
  'Politics',
  'Jewish history',
  'Türkiye',
  'Global marketing',
  'History of India',
  'Organisation of Islamic Cooperation',
  'Afghanistan',
  'Vietnam',
  'Ottoman Empire',
  'Empire of Japan',
  'Weimar Republic',
  'Prussia',
  'Nazi Germany',
  'East Germany',
  'West Germany',
  'Trade',
  'Commerce',
  'Property',
  'Retail',
  'Chinese Civil War',
  'History of China',
  'Sri Lankan civil war',
  '3D printing',
  'Investing',
  'History of Russia',
  'Russian Empire',
  'British Hong Kong',
  'Human genetics',
  'Human evolution',
  'World history',
  'Thinking, Fast and Slow',
  'Victorian era',
  'Renaissance',
  'Romila Thapar',
  'Ramachandra Guha',
  'Karan Thapar',
  'Yogendra Yadav',
  'Indo-Aryan migrations',
  'Normandy landings',
  'Adolf Hitler',
  'Hirohito',
  'Joseph Stalin',
  'Franklin D. Roosevelt',
  'Winston Churchill',
  'Abhijit Iyer-Mitra',
  'Audrey Truschke',
  'Indian National Congress',
  'Bharatiya Janata Party',
  'All India Anna Dravida Munnetra Kazhagam',
  'Dravida Munnetra Kazhagam',
  'M.G. Ramachandran',
  'C. N. Annadurai',
  'K. Kamaraj',
  'C. Rajagopalachari',
  'J. Jayalalithaa',
  'Benito Mussolini',
  'Mao Zedong',
  'Benjamin Franklin',
  'Thomas Jefferson',
  'John Adams',
  'George Washington',
  'Ulysses S. Grant',
  'Abraham Lincoln',
  'United Arab Emirates',
  'Saudi Arabia',
  'Deng Xiaoping',
  'Lee Kuan Yew',
  'Tamil',
  'Tamil literature',
  'English Literature',
  'South India',
  'Ireland',
  'History of Greece',
  'Milton Friedman',
  'Friedrich Hayek',
  'Walter E. Williams',
  'Thomas Sowell',
  'Innovation',
  'Corporate governance',
  'Management consulting',
  'Robotics',
  'Automation',
  'Corporate finance',
  'India',
  'Capital market',
  'US',
  'History of Israel',
  'Food',
  'Tamilaga Vettri Kazhagam',
  'Walmart',
  'Amazon.com',
  'Tesla',
  'McDonald\'s',
  'Google',
  'Wendy\'s',
  'The Coca-Cola Company',
  'Starbucks',
  'Burger King',
  'Apple',
  'Procter & Gamble',
  '7-Eleven',
  'Target Corporation',
  'Costco Wholesale Corp',
  'Meta',
  'Microsoft',
  'Domino\'s',
  'Nvidia',
  'iOS',
  'Android',
  'TSMC',
  'Reliance Retail Ventures Limited',
  'Flipkart',
  'Chick-fil-A',
  'Motilal Oswal Financial Services',
  'Motilal Oswal NASDAQ 100 ETF',
  'Investment management',
  'KFC',
  'Subway',
  'Javier Milei',
  'Panama Canal',
  'Panama',
  'British Virgin Islands',
  'Cayman Islands',
  'Luxembourg',
  'Wales',
  'England',
  'Scotland',
  'Georgia',
  'Malaysia',
  'Digital marketing',
  'Taco Bell',
  'Corruption in India',
  'Corruption in Japan',
  'Corruption in China',
  'Liberal Party of Canada',
  'Conservative Party of Canada',
  'Conservative Party',
  'Reform UK',
  'Labour Party',
  'Libertarian Party',
  'Democratic Party',
  'Republican Party',
  'Realty Income',
  'Vodafone Idea Limited',
  'OpenAI',
  'Jio',
  'Temu',
  'Alibaba Group',
  'DeepSeek',
  'Anthropic',
  'Perplexity AI',
  'Bridgewater Associates',
  'United States Congress',
  'Scion Asset Management',
  'Elon Musk',
  'Waymo',
  'Anthropology',
  'Jeff Bezos',
  'Peter Lynch',
  'K. Annamalai',
  'Scott Adams',
  'Rashtriya Swayamsevak Sangh',
  'Tamil Nadu Congress Committee',
  'Bharatiya Janata Party – Tamil Nadu',
  'Naam Tamilar Katchi',
  'Petroleum',
  'National Security Agency',
  'Central Intelligence Agency',
  'Federal Bureau of Investigation',
  'OnePlus',
  'Nothing',
  'Zomato',
  'Swiggy',
  'Amazon Web Services'
] as const;
